// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require("chromedriver");

for(let i = 0;i<3;i++){
  console.log(i);
}

describe('Login and add supervisor', function() {
  this.timeout(600000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login and add supervisor', async function() {
    await driver.get("https://wrmstormhotfixscs.azurewebsites.net/default.aspx")
    await driver.manage().window().setRect({ width: 1280, height: 720 })
    for(let out=0; out<2; out++){
      driver.findElement(By.tagName("html")).sendKeys(Key.chord(Key.CONTROL,Key.SUBTRACT));
     }
    // Login Page
    await driver.findElement(By.id("AdvanceSearch_ASPxButton1_CD")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("nakorn_ton@hotmail.com.wrmsoftware.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Multitenant01@")
    await driver.findElement(By.id("btn_VendorLogin")).click()

    // Access Page
    await driver.findElement(By.xpath("(//table[@class='dxeButtonEditSys dxeButtonEdit_DevEx']//td)[2]")).click()
    await driver.sleep(1000)
    await driver.findElement(By.xpath("(//td[@class='dxgv']//td)[3]")).click()
    await driver.sleep(1000)
    await driver.findElement(By.xpath("(//img[@alt='v'])[2]")).click()
    await driver.sleep(1000)
    await driver.findElement(By.xpath("//td[@id='ASPxPanel2_ContentPlaceHolder1_gluEvents_DDD_gv_tccell6_0']//td[1]")).click()
    await driver.sleep(5000)

    // Select for Add Supervisor
    await driver.findElement(By.xpath("//span[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_cpnRefreshGridViewAndSummary_ASPxGridView1_DXSelBtn0_D']")).click()
    await driver.findElement(By.xpath("//span[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_cpnRefreshGridViewAndSummary_ASPxGridView1_DXSelBtn1_D']")).click()
    await driver.findElement(By.xpath("//span[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_cpnRefreshGridViewAndSummary_ASPxGridView1_DXSelBtn2_D']")).click()
    await driver.sleep(3000)
    await driver.findElement(By.xpath("(//div[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_btnAssignSupervisor']//div)[1]")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignSupervisor_cpnRefreshBirdDog_tkbAssignSupervisor_I")).sendKeys("Nakorn SoCo")
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignSupervisor_cpnRefreshBirdDog_tkbAssignSupervisor_I")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("#ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignSupervisor_cpnBtnAssignSupervisor_btnPucAssignSupervisor_CD > .dx-vam:nth-child(3)")).click()
    await driver.sleep(5000)

    // Add supervisor | check notification message 
    try {
      const noti = await driver.findElement(By.id("TopPanel_notifyDiv_Content")).getText()
      assert.strictEqual(noti,'The Supervisor has been assigned to selected resource pool/crew sheet successfully.')
      console.log("This notification is pass")
    } catch(error) {
      console.log("Error: ", error)
    }

    // Add Location
    await driver.findElement(By.xpath("//div[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_btnAssignDestination']")).click()
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_UtilityLocations_rdnUSCUtilityLocation_RB3_I_D")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_UtilityLocations_cpnUSCUtilityLocation_cbUSCUtilityLocationDestination_B-1Img")).click()
    await driver.sleep(3000);
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_UtilityLocations_cpnUSCUtilityLocation_cbUSCUtilityLocationDestination_I")).sendKeys("Mobile - Jackson")
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_UtilityLocations_cpnUSCUtilityLocation_cbUSCUtilityLocationDestination_B-1Img")).click()
    await driver.sleep(3000)

    // Add location | check notification message 
    try {
      const noti1 = await driver.findElement(By.id("TopPanel_notifyDiv_Content")).getText()
      assert.strictEqual(noti1,'The destination has been assigned to selected resource pool/crew sheet successfully.')
      console.log("This notification is pass")
    } catch(error) {
      console.log("Error: ", error)
    }
    

    //Add date time and text   
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_dtETAAssignDestination_B-1Img")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_dtETAAssignDestination_I")).sendKeys("06/01/2565 06:30 AM")
    await driver.sleep(3000)
    /* 
    await driver.findElement(By.xpath("(//td[contains(@class,'dxeCalendarDay_DevEx dxeCalendarToday_DevEx')])[2]")).click()
    await driver.findElement(By.xpath("//input[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_dtETAAssignDestination_DDD_C_TE_I']")).clear();
    await driver.sleep(3000)
    await driver.findElement(By.xpath("//input[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_dtETAAssignDestination_DDD_C_TE_I']")).sendKeys('06:30 AM')
    */
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_dtETAAssignDestination_I")).sendKeys(Key.ENTER)
    await driver.sleep(3000)    
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_eta_comment_ASPxTextBox_I")).click()
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_eta_comment_ASPxTextBox_I")).sendKeys("See you in the morning.")
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignDestination_cpnBtnAssignDestinationSave_btnPucAssignDestination_CD")).click()
    await driver.sleep(15000)
    
    // Add Event
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_btnAssignEventImg")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignEvent_assign_event_mscwf_ASPxComboBox_CallbackPanel_assign_event_mscwf_ASPxComboBox_I")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignEvent_assign_event_mscwf_ASPxComboBox_CallbackPanel_assign_event_mscwf_ASPxComboBox_DDD_L_LBI9T0")).click()
    await driver.sleep(3000)
    await driver.findElement(By.xpath("//img[@id='ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignEvent_dtEventDate_B-1Img']")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignEvent_dtEventDate_I")).sendKeys("06/01/2565 12:00 AM")
    await driver.sleep(3000)
    await driver.findElement(By.id("ASPxPanel2_ContentPlaceHolder1_cpnTokenDeleted_cpnMain_pucBtnAssignEvent_dtEventDate_I")).sendKeys(Key.ENTER)
    await driver.sleep(3000)
    await driver.findElement(By.xpath("//span[text()='Apply Event']")).click()
    await driver.sleep(3000)

    // Add location | check notification message 
    try {
      const noti2 = await driver.findElement(By.id("TopPanel_notifyDiv_Content")).getText()
      assert.strictEqual(noti2,'The event has been applied to selected resource pool/crew sheet.')
      console.log("This notification is pass")
    } catch(error) {
      console.log("Error: ", error)
    }

    // Check move to
    await driver.findElement(By.id("TopPanel_gluEvents_B-1Img")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("TopPanel_gluEvents_DDD_gv_DXDataRow11")).click()
    await driver.sleep(10000)
    
  })
})
